[package]
name = "Solutions_THrough_RUst"
version = "0.1.0"
edition = "2018"

# See more keys and heir definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
C opt-level=3
[dependencies]
